TB8504: camera: Add missing display include path
hardware/qcom-caf/msm8996/display/libqdutils/qdMetaData.h:33:10: fatal error: 'color_metadata.h' file not found
#include <color_metadata.h>
         ^~~~~~~~~~~~~~~~~~