TB8504: camera: Add missing gralloc include path
device/lenovo/TB8504/camera/QCamera2/HAL3/QCamera3HWI.cpp:46:10: fatal error: 'gralloc_priv.h' file not found
#include "gralloc_priv.h"
         ^~~~~~~~~~~~~~~~